# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michel Cordeiro
email: pere.cordeiro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Blog
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://br.linkedin.com/in/michelcordeiro" # the base hostname & protocol for your site

#sidebar
default-image: michel.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: michelcordeiro

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/

analytics: UA-84556164-1
disqus-shortname: michelcordeiro

#social
facebook: https://www.facebook.com/michel.cordeiro.79
twitter: http://twitter.com/@code_shell
github: https://github.com/MichelCordeiro
linkedin: https://br.linkedin.com/in/michelcordeiro

#facebook like box
fb-app-id: 294632780910117
fb-page-url: https://www.facebook.com/agilemaranhao/
fb-page-title: Agile MA


sass:
  style: compressed

gems: [jekyll-paginate, jekyll-seo-tag]

